"use client";

import { usePathname } from "next/navigation";
import { Inter } from "next/font/google";
// import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../../theme";
import NavBar from "../../components/SideNavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <NavBar> {children}</NavBar>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
